<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mahir Tajwar">
<meta name="dcterms.date" content="2025-04-17">

<title>Modeling Ecosystem Metabolism in Stephens Lake, Franklin Tennessee</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="semester-project_files/libs/clipboard/clipboard.min.js"></script>
<script src="semester-project_files/libs/quarto-html/quarto.js"></script>
<script src="semester-project_files/libs/quarto-html/popper.min.js"></script>
<script src="semester-project_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="semester-project_files/libs/quarto-html/anchor.min.js"></script>
<link href="semester-project_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="semester-project_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="semester-project_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="semester-project_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="semester-project_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Modeling Ecosystem Metabolism in Stephens Lake, Franklin Tennessee</h1>
<p class="subtitle lead">EES 4891/5891: Probability and Statistics for Geosciences</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mahir Tajwar </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 17, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<p>Set up R environment by loading the necessary libraries</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load libraries</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(suncalc)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(LakeMetabolizer)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Freshwater ecosystems play a critical role in global biogeochemical cycling by regulating carbon and oxygen fluxes between aquatic environments and the atmosphere. Understanding lake metabolism — the balance between gross primary production (GPP), ecosystem respiration (ER), and net ecosystem productivity (NEP) — is essential for evaluating ecosystem health, productivity, and how these systems respond to climate variability and anthropogenic impacts.</p>
<p>Lake metabolism studies provide a quantitative framework for interpreting the diel (24-hour) patterns of oxygen fluctuations driven by photosynthesis during the day and respiration at night. By analyzing these oxygen patterns, researchers can estimate how much organic carbon is being produced and consumed within the aquatic system. High-frequency metabolism modeling is particularly valuable for capturing these dynamics at sub-daily scales, revealing short-term ecological processes that would otherwise be obscured by daily averages.</p>
<p>In this project, I focus on Stephens Lake, a shallow headwater lake located in Franklin, Tennessee. The lake is well-mixed, oxygen-rich, and oligotrophic, making it an ideal system for exploring diel patterns in metabolism under relatively low-nutrient and low-stratification conditions. From October 18 to 20, 2024, I conducted a 48-hour field campaign during the fall season, collecting dissolved oxygen and temperature data at half-meter depth intervals every hour. These continuous measurements form the foundation for modeling ecosystem metabolism.</p>
<p>To supplement these in-situ measurements, I derived additional atmospheric and environmental parameters. Wind speed data were extracted from the ERA5-Land hourly reanalysis dataset using Google Earth Engine. Photosynthetically active radiation (PAR) — a key driver of daytime primary production — was modeled using the <code>suncalc</code> package in R, based on solar elevation angles at the lake’s coordinates. Together, these datasets allow for a complete input matrix to estimate GPP, ER, and NEP using the <code>LakeMetabolizer</code> package in R, specifically applying the ordinary least squares (OLS) method for modeling metabolism at an hourly resolution.</p>
<p>Through this project, I aim to quantify diel and seasonal metabolism dynamics and better understand carbon cycling in a temperate lake ecosystem. This research also provides a foundation for future seasonal comparisons and helps demonstrate how open-source tools in R can be used to analyze and visualize high-frequency ecosystem processes.</p>
<section id="date-set" class="level3">
<h3 class="anchored" data-anchor-id="date-set">Date set</h3>
<p>The dataset consists of:</p>
<ul>
<li><p><strong>DO and temperature values</strong> at 0.5 m depth measured every hour from October 18, 2024 at 18:00 to October 20, 2024 at 18:00.</p></li>
<li><p><strong>Wind speed data</strong> retrieved hourly from ERA5-Land using Google Earth Engine.</p></li>
<li><p><strong>PAR (Photosynthetically Active Radiation)</strong> values calculated using the <code>suncalc</code> package in R based on solar elevation angle.</p></li>
<li><p>All data were compiled and merged into a single <code>.xlsx</code> file for use with the <code>LakeMetabolizer</code> package.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>ts.data <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"ERA5_StephensLake_Weather_Oct2024_WithUnits.xlsx"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="descriptive-statistics" class="level2">
<h2 class="anchored" data-anchor-id="descriptive-statistics">Descriptive Statistics</h2>
<p>To better understand the distribution and variability of environmental drivers that influence lake metabolism, we conducted descriptive statistical analysis on the main input variables: dissolved oxygen (DO), water temperature, wind speed, and modeled photosynthetically active radiation (PAR). Summary statistics such as mean, standard deviation, and range were calculated. Additionally, histograms and kernel density plots were used to visualize the distribution of these variables.</p>
<p>We assessed whether each variable follows a normal distribution using Q–Q plots. Since our dataset spans 48 hours at hourly resolution, the diel patterns introduce variability that might cause deviations from normality—especially for variables like PAR, which are naturally zero at night. Finally, we generated a pairs plot to explore correlations among variables, particularly between PAR, DO, and GPP-driving metrics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary libraries</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the Excel file</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>data_path <span class="ot">&lt;-</span> <span class="st">"/Users/mahirtajwar/Desktop/EES-5891/semester-project-mahirtajwar15/ERA5_StephensLake_Weather_Oct2024_WithUnits.xlsx"</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(data_path)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View column names and basic summary</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 49
Columns: 5
$ datetime  &lt;dttm&gt; 2024-10-18 18:00:00, 2024-10-18 19:00:00, 2024-10-18 20:00:…
$ doobs_0.5 &lt;dbl&gt; 8.38, 8.15, 8.39, 8.34, 7.86, 7.81, 7.62, 7.72, 8.04, 7.96, …
$ wtr_0.5   &lt;dbl&gt; 17.085016, 15.008844, 13.687311, 12.676157, 11.974557, 11.41…
$ wnd_2.0   &lt;dbl&gt; 1.8067073, 1.8791279, 1.8410201, 1.8185450, 1.7752427, 1.746…
$ par       &lt;dbl&gt; 115.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    datetime                     doobs_0.5        wtr_0.5      
 Min.   :2024-10-18 18:00:00   Min.   :7.570   Min.   : 5.824  
 1st Qu.:2024-10-19 06:00:00   1st Qu.:7.760   1st Qu.: 9.614  
 Median :2024-10-19 18:00:00   Median :8.000   Median :13.432  
 Mean   :2024-10-19 18:00:00   Mean   :8.107   Mean   :14.190  
 3rd Qu.:2024-10-20 06:00:00   3rd Qu.:8.390   3rd Qu.:19.499  
 Max.   :2024-10-20 18:00:00   Max.   :9.030   Max.   :22.645  
    wnd_2.0            par        
 Min.   :0.1854   Min.   :   0.0  
 1st Qu.:0.6581   1st Qu.:   0.0  
 Median :1.1146   Median : 115.0  
 Mean   :1.1406   Mean   : 632.4  
 3rd Qu.:1.6533   3rd Qu.:1225.8  
 Max.   :1.9185   Max.   :2161.8  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select variables of interest</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>vars <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(wtr_0<span class="fl">.5</span>, doobs_0<span class="fl">.5</span>, wnd_2<span class="fl">.0</span>, par)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename for clarity</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(vars) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Temperature"</span>, <span class="st">"DO"</span>, <span class="st">"WindSpeed"</span>, <span class="st">"PAR"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot histograms with density curves</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>vars <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">"Variable"</span>, <span class="at">values_to =</span> <span class="st">"Value"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Value, <span class="at">fill =</span> Variable)) <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> ..density..), <span class="at">bins =</span> <span class="dv">30</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">position =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Variable, <span class="at">scales =</span> <span class="st">"free"</span>, <span class="at">ncol =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Environmental Variables"</span>,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Value"</span>, <span class="at">y =</span> <span class="st">"Density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The dot-dot notation (`..density..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(density)` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="semester-project_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The distribution plots (histograms with kernel density curves) provide a snapshot of the variability and skewness present in the key environmental parameters used in this lake metabolism study. Dissolved oxygen (DO) shows a slightly left-skewed distribution, centered around 8.3–8.5 mg/L, indicating relatively stable oxygen conditions with a few lower values likely corresponding to nighttime respiration. Photosynthetically active radiation (PAR) exhibits strong positive skewness, with most values concentrated around zero, reflecting the expected diel cycle of low irradiance during night and sharp peaks during midday hours. Temperature data are moderately spread between 6–22°C, showing no extreme outliers and following a more uniform pattern, possibly due to a consistent weather trend over the 48-hour sampling period. Wind speed shows mild right-skewness, indicating occasional gusty conditions but with most wind speeds clustering around 1–1.5 m/s.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load library</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert your vars data frame to long format</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>vars_long <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(vars, <span class="at">cols =</span> <span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">"Variable"</span>, <span class="at">values_to =</span> <span class="st">"Value"</span>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate Q-Q plots using ggplot2</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>qq_plots <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(vars_long, <span class="fu">aes</span>(<span class="at">sample =</span> Value)) <span class="sc">+</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>(<span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Variable, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Q-Q Plots of Key Variables"</span>)</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Print</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(qq_plots)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="semester-project_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The Q-Q plots further evaluate whether the variables follow a normal distribution. DO and temperature variables largely follow the reference line, suggesting a close-to-normal distribution with minor deviations at the tails. Wind speed shows some deviation from normality at higher values, reflecting its slight skewness. In contrast, PAR deviates considerably from the normal distribution, particularly in the lower and upper quantiles, confirming its strong skewness and non-normality—likely due to its zero values at night and sharp peaks during the day. These visual diagnostics help inform the appropriate statistical methods to be applied later, such as transformations or non-parametric tests where normality assumptions do not hold.</p>
</section>
<section id="research-questions" class="level2">
<h2 class="anchored" data-anchor-id="research-questions">Research Questions</h2>
<ol type="1">
<li><p>How does lake metabolism vary diurnally across the 48-hour sampling period?</p></li>
<li><p>What is the relationship between PAR and GPP across diel cycles?</p></li>
<li><p>Are nighttime NEP values consistently negative, indicating dominant respiration?</p></li>
<li><p>How does GPP compare to ER across the two days, and what does that imply about autotrophic vs.&nbsp;heterotrophic status?</p></li>
</ol>
</section>
<section id="hypotheses-and-tests" class="level2">
<h2 class="anchored" data-anchor-id="hypotheses-and-tests">Hypotheses and Tests</h2>
<section id="hypotheses" class="level3">
<h3 class="anchored" data-anchor-id="hypotheses">Hypotheses</h3>
<ul>
<li><p><strong>H1</strong>: <strong>Gross Primary Production (GPP) will exhibit strong diurnal patterns, peaking during daylight hours and dropping to near zero at night.</strong><br>
</p>
<p>This hypothesis is based on the fundamental understanding that GPP is driven by photosynthesis, which depends on sunlight. During daylight hours, the availability of photosynthetically active radiation (PAR) enables autotrophic organisms (such as phytoplankton and aquatic plants) to convert light energy into organic carbon. At night, the absence of sunlight halts photosynthesis, and GPP is expected to approach zero.</p></li>
<li><p><strong>H2</strong>: <strong>Ecosystem Respiration (ER) will remain relatively stable throughout the diel cycle, with potential increases during nighttime.</strong><br>
</p>
<p>Respiration in aquatic systems occurs continuously as organisms break down organic matter to produce energy. While ER is generally less variable than GPP, it may show slight increases at night due to greater oxygen availability from mixing, or due to continued microbial and heterotrophic activity in the absence of photosynthesis.</p></li>
<li><p><strong>H3</strong>: <strong>Net Ecosystem Productivity (NEP) will be positive during the day and negative at night, indicating a shift from photosynthetic dominance to respiratory dominance.</strong><br>
</p>
<p>NEP represents the balance between GPP and ER. During the day, GPP is expected to exceed ER, resulting in positive NEP values (net oxygen gain). At night, with GPP falling to zero and ER continuing, NEP is expected to become negative (net oxygen loss). This diel shift in NEP highlights the natural metabolic rhythm of the lake ecosystem.</p></li>
</ul>
</section>
<section id="methods" class="level3">
<h3 class="anchored" data-anchor-id="methods">Methods</h3>
<p>We used the <code>OLS_inst</code> function from the LakeMetabolizer package to estimate hourly GPP, ER, and NEP values using the classic OLS (Ordinary Least Squares) approach. PAR was calculated using the solar elevation angle, and wind speed was used to compute gas exchange rates (k600) and k.gas.</p>
<p>Code block showing calculation of PAR values using Suncalc</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load libraries</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(suncalc)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Set Stephens Lake coordinates</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>lat <span class="ot">&lt;-</span> <span class="fl">35.94</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>lon <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">87.02</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Fall sampling window in **local time** (America/Chicago)</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>start_fall_local <span class="ot">&lt;-</span> <span class="fu">force_tz</span>(<span class="fu">ymd_hm</span>(<span class="st">"2024-10-18 18:00"</span>), <span class="at">tzone =</span> <span class="st">"America/Chicago"</span>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>end_fall_local   <span class="ot">&lt;-</span> <span class="fu">force_tz</span>(<span class="fu">ymd_hm</span>(<span class="st">"2024-10-20 18:00"</span>), <span class="at">tzone =</span> <span class="st">"America/Chicago"</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Create hourly sequence in local time</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>timestamps_fall_local <span class="ot">&lt;-</span> <span class="fu">seq</span>(start_fall_local, end_fall_local, <span class="at">by =</span> <span class="st">"hour"</span>)</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to UTC for accurate solar position calculation</span></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>timestamps_fall_utc <span class="ot">&lt;-</span> <span class="fu">with_tz</span>(timestamps_fall_local, <span class="at">tzone =</span> <span class="st">"UTC"</span>)</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate solar angle based on UTC</span></span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>sun_pos <span class="ot">&lt;-</span> <span class="fu">getSunlightPosition</span>(<span class="at">date =</span> timestamps_fall_utc, <span class="at">lat =</span> lat, <span class="at">lon =</span> lon)</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Create data frame</span></span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>sol_data_fall <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">datetime_local =</span> timestamps_fall_local,</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">datetime_utc =</span> timestamps_fall_utc,</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">elevation =</span> sun_pos<span class="sc">$</span>altitude <span class="sc">*</span> <span class="dv">180</span> <span class="sc">/</span> pi  <span class="co"># Convert from radians to degrees</span></span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a><span class="co"># === NEW: Calculate irradiance and PAR with smoother dusk/dawn transition ===</span></span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a>sol_data_fall <span class="ot">&lt;-</span> sol_data_fall <span class="sc">%&gt;%</span></span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb13-33"><a href="#cb13-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">irradiance =</span> <span class="fu">ifelse</span>(elevation <span class="sc">&gt;</span> <span class="sc">-</span><span class="dv">6</span>,</span>
<span id="cb13-34"><a href="#cb13-34" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">pmax</span>(<span class="dv">50</span>, <span class="dv">1367</span> <span class="sc">*</span> <span class="fu">sin</span>(elevation <span class="sc">*</span> pi <span class="sc">/</span> <span class="dv">180</span>)),</span>
<span id="cb13-35"><a href="#cb13-35" aria-hidden="true" tabindex="-1"></a>                        <span class="dv">0</span>),  <span class="co"># allow minimum irradiance at twilight</span></span>
<span id="cb13-36"><a href="#cb13-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">PAR =</span> irradiance <span class="sc">*</span> <span class="fl">2.3</span>  <span class="co"># µmol/m²/s</span></span>
<span id="cb13-37"><a href="#cb13-37" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb13-38"><a href="#cb13-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-39"><a href="#cb13-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Export to CSV</span></span>
<span id="cb13-40"><a href="#cb13-40" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(sol_data_fall[, <span class="fu">c</span>(<span class="st">"datetime_local"</span>, <span class="st">"PAR"</span>)], </span>
<span id="cb13-41"><a href="#cb13-41" aria-hidden="true" tabindex="-1"></a>          <span class="st">"StephensLake_PAR_Fall_Only_SMOOTHED.csv"</span>, </span>
<span id="cb13-42"><a href="#cb13-42" aria-hidden="true" tabindex="-1"></a>          <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Code block showing LakeMetabolizer OLS modeling for GPP, ER, NEP</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(LakeMetabolizer)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>data.path <span class="ot">=</span> <span class="fu">system.file</span>(<span class="st">'extdata/'</span>, <span class="at">package=</span><span class="st">"LakeMetabolizer"</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>ts.data <span class="ot">=</span> <span class="fu">read_excel</span> (<span class="st">'/Users/mahirtajwar/Desktop/EES-5891/semester-project-mahirtajwar15/ERA5_StephensLake_Weather_Oct2024_WithUnits.xlsx'</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co">#calculate U10 and add it back onto the original</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>u10 <span class="ot">=</span> <span class="fu">wind.scale</span>(ts.data)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>ts.data <span class="ot">=</span> <span class="fu">rmv.vars</span>(ts.data, <span class="st">'wnd'</span>, <span class="at">ignore.offset=</span><span class="cn">TRUE</span>) <span class="co">#drop old wind speed column</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>ts.data <span class="ot">=</span> <span class="fu">merge</span>(ts.data, u10) <span class="co">#merge new u10 into big dataset</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a><span class="co">#Now calculate k600 using the Cole method</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>k600.cole <span class="ot">=</span> <span class="fu">k.cole</span>(ts.data)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>ts.data <span class="ot">=</span> <span class="fu">merge</span>(ts.data, k600.cole)</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>kgas <span class="ot">=</span> <span class="fu">k600.2.kGAS</span>(ts.data)</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>ts.data <span class="ot">=</span> <span class="fu">rmv.vars</span>(<span class="fu">merge</span>(kgas, ts.data), <span class="st">'k600'</span>)</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>o2.sat <span class="ot">=</span> <span class="fu">o2.at.sat</span>(ts.data[,<span class="fu">c</span>(<span class="st">'datetime'</span>,<span class="st">'wtr_0.5'</span>)])</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>ts.data <span class="ot">=</span> <span class="fu">merge</span>(o2.sat, ts.data)</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>z.mix <span class="ot">=</span> <span class="fu">ts.meta.depths</span>(<span class="fu">get.vars</span>(ts.data, <span class="st">'wtr'</span>), <span class="at">seasonal=</span><span class="cn">TRUE</span>)</span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(z.mix) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">'datetime'</span>,<span class="st">'z.mix'</span>, <span class="st">'bottom'</span>)</span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a><span class="co">#set z.mix to bottom of lake when undefined</span></span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>z.mix[z.mix<span class="sc">$</span>z.mix <span class="sc">&lt;=</span> <span class="dv">0</span> <span class="sc">|</span> <span class="fu">is.na</span>(z.mix<span class="sc">$</span>z.mix), <span class="st">'z.mix'</span>] <span class="ot">&lt;-</span> <span class="fl">1.6</span>  <span class="co"># replace with actual max depth of your lake</span></span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a>ts.data <span class="ot">=</span> <span class="fu">merge</span>(ts.data, z.mix[,<span class="fu">c</span>(<span class="st">'datetime'</span>,<span class="st">'z.mix'</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>calc.freq <span class="ot">&lt;-</span> <span class="cf">function</span>(datetime) {</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  freq <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">Mode</span>(<span class="dv">1</span><span class="sc">/</span><span class="fu">diff</span>(<span class="fu">date2doy</span>(datetime))))</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>Mode <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  ux <span class="ot">&lt;-</span> <span class="fu">unique</span>(x)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  ux[<span class="fu">which.max</span>(<span class="fu">tabulate</span>(<span class="fu">match</span>(x, ux)))]</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>date2doy <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stopifnot</span>(<span class="fu">any</span>(<span class="fu">grepl</span>(<span class="st">"^POSIX"</span>, <span class="fu">class</span>(x[<span class="dv">1</span>]))))</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  day <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">format</span>(x, <span class="st">"%j"</span>))</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  pat <span class="ot">&lt;-</span> <span class="fu">quote</span>(<span class="st">"([0-9]{2}:){2}[0-9]{2}"</span>)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  midnight <span class="ot">&lt;-</span> <span class="fu">as.POSIXct</span>(<span class="fu">gsub</span>(pat, <span class="st">"00:00:00"</span>, x), <span class="at">tz =</span> <span class="st">"GMT"</span>)</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  frac <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">difftime</span>(x, midnight, <span class="at">units =</span> <span class="st">"days"</span>))</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  day <span class="sc">+</span> frac</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>OLS_inst <span class="ot">&lt;-</span> <span class="cf">function</span>(datetime, do.obs, do.sat, k.gas, z.mix, irr, wtr, ...) {</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>  nobs <span class="ot">&lt;-</span> <span class="fu">length</span>(do.obs)</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>  mo.args <span class="ot">&lt;-</span> <span class="fu">list</span>(...)</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">any</span>(z.mix <span class="sc">&lt;=</span> <span class="dv">0</span>)) <span class="fu">stop</span>(<span class="st">"z.mix must be greater than zero."</span>)</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">any</span>(wtr <span class="sc">&lt;=</span> <span class="dv">0</span>)) <span class="fu">stop</span>(<span class="st">"all wtr must be positive."</span>)</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>  freq <span class="ot">&lt;-</span> <span class="fu">calc.freq</span>(datetime)</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>  do.diff <span class="ot">&lt;-</span> <span class="fu">diff</span>(do.obs)</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>  inst_flux <span class="ot">&lt;-</span> (k.gas<span class="sc">/</span>freq) <span class="sc">*</span> (do.sat <span class="sc">-</span> do.obs)</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>  flux <span class="ot">&lt;-</span> inst_flux[<span class="sc">-</span>nobs]</span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a>  noflux.do.diff <span class="ot">&lt;-</span> do.diff <span class="sc">-</span> flux<span class="sc">/</span>z.mix[<span class="sc">-</span>nobs]</span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a>  lntemp <span class="ot">&lt;-</span> <span class="fu">log</span>(wtr)</span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a>  mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(noflux.do.diff <span class="sc">~</span> irr[<span class="sc">-</span>nobs] <span class="sc">+</span> lntemp[<span class="sc">-</span>nobs] <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a>  rho <span class="ot">&lt;-</span> mod[[<span class="dv">1</span>]][<span class="dv">2</span>]</span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a>  iota <span class="ot">&lt;-</span> mod[[<span class="dv">1</span>]][<span class="dv">1</span>]</span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a>  mod.matrix <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(mod)</span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a>  gpp <span class="ot">&lt;-</span> iota <span class="sc">*</span> mod.matrix[, <span class="dv">1</span>]<span class="sc">*</span>freq</span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a>  resp <span class="ot">&lt;-</span> rho <span class="sc">*</span> mod.matrix[, <span class="dv">2</span>]<span class="sc">*</span>freq</span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a>  nep <span class="ot">&lt;-</span> gpp <span class="sc">+</span> resp</span>
<span id="cb15-38"><a href="#cb15-38" aria-hidden="true" tabindex="-1"></a>  datetime <span class="ot">&lt;-</span> datetime[<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb15-39"><a href="#cb15-39" aria-hidden="true" tabindex="-1"></a>  inst.results <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">mod =</span> mod, <span class="at">metab =</span> <span class="fu">data.frame</span>(<span class="at">datetime =</span> datetime, <span class="at">GPP =</span> gpp, <span class="at">R =</span> resp, <span class="at">NEP =</span> nep, <span class="at">KO2 =</span> k.gas[<span class="sc">-</span>nobs]))</span>
<span id="cb15-40"><a href="#cb15-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(inst.results)</span>
<span id="cb15-41"><a href="#cb15-41" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run OLS metabolism model</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>ols.inst.res <span class="ot">&lt;-</span> <span class="fu">OLS_inst</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">datetime =</span> ts.data<span class="sc">$</span>datetime,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">do.obs =</span> ts.data<span class="sc">$</span>doobs_0<span class="fl">.5</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">do.sat =</span> ts.data<span class="sc">$</span>do.sat,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">k.gas =</span> ts.data<span class="sc">$</span>k.gas,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">z.mix =</span> ts.data<span class="sc">$</span>z.mix,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">irr =</span> ts.data<span class="sc">$</span>par,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">wtr =</span> ts.data<span class="sc">$</span>wtr_0<span class="fl">.5</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert output to data frame</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>ols.inst.res.df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(ols.inst.res<span class="sc">$</span>metab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>calc.freq <span class="ot">&lt;-</span> <span class="cf">function</span> (datetime) </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  freq <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">Mode</span>(<span class="dv">1</span><span class="sc">/</span><span class="fu">diff</span>(<span class="fu">date2doy</span>(datetime))))</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>Mode <span class="ot">&lt;-</span> <span class="cf">function</span> (x) </span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  ux <span class="ot">&lt;-</span> <span class="fu">unique</span>(x)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  ux[<span class="fu">which.max</span>(<span class="fu">tabulate</span>(<span class="fu">match</span>(x, ux)))]</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>date2doy <span class="ot">&lt;-</span> <span class="cf">function</span> (x) </span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stopifnot</span>(<span class="fu">any</span>(<span class="fu">grepl</span>(<span class="st">"^POSIX"</span>, <span class="fu">class</span>(x[<span class="dv">1</span>]))))</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>  day <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">format</span>(x, <span class="st">"%j"</span>))</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>  pat <span class="ot">&lt;-</span> <span class="fu">quote</span>(<span class="st">"([0-9]{2}:){2}[0-9]{2}"</span>)</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>  midnight <span class="ot">&lt;-</span> <span class="fu">as.POSIXct</span>(<span class="fu">gsub</span>(pat, <span class="st">"00:00:00"</span>, x), <span class="at">tz =</span> <span class="st">"GMT"</span>)</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>  frac <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">difftime</span>(x, midnight, <span class="at">units =</span> <span class="st">"days"</span>))</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>  day <span class="sc">+</span> frac</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>OLS_inst <span class="ot">&lt;-</span> <span class="cf">function</span> (datetime, do.obs, do.sat, k.gas, z.mix, irr, wtr, ...) </span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>  <span class="co"># complete.inputs(do.obs = do.obs, do.sat = do.sat, k.gas = k.gas, </span></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>  <span class="co">#                 z.mix = z.mix, irr = irr, wtr = wtr, error = TRUE)</span></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>  nobs <span class="ot">&lt;-</span> <span class="fu">length</span>(do.obs)</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>  mo.args <span class="ot">&lt;-</span> <span class="fu">list</span>(...)</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">any</span>(z.mix <span class="sc">&lt;=</span> <span class="dv">0</span>)) {</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stop</span>(<span class="st">"z.mix must be greater than zero."</span>)</span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">any</span>(wtr <span class="sc">&lt;=</span> <span class="dv">0</span>)) {</span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stop</span>(<span class="st">"all wtr must be positive."</span>)</span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a>  <span class="co"># if ("datetime" %in% names(mo.args)) {</span></span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>  <span class="co">#   datetime &lt;- mo.args$datetime</span></span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>  <span class="co">#   freq &lt;- calc.freq(datetime)</span></span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a>  <span class="co">#   if (nobs != freq) {</span></span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a>  <span class="co">#     bad.date &lt;- format.Date(datetime[1], format = "%Y-%m-%d")</span></span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a>  <span class="co">#     warning("number of observations on ", bad.date, " (", </span></span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a>  <span class="co">#             nobs, ") ", "does not equal estimated sampling frequency", </span></span>
<span id="cb17-41"><a href="#cb17-41" aria-hidden="true" tabindex="-1"></a>  <span class="co">#             " (", freq, ")", sep = "")</span></span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a>  <span class="co">#   }</span></span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a>  <span class="co"># }</span></span>
<span id="cb17-44"><a href="#cb17-44" aria-hidden="true" tabindex="-1"></a>  <span class="co"># else {</span></span>
<span id="cb17-45"><a href="#cb17-45" aria-hidden="true" tabindex="-1"></a>  <span class="co">#   warning("datetime not found, inferring sampling frequency from # of observations")</span></span>
<span id="cb17-46"><a href="#cb17-46" aria-hidden="true" tabindex="-1"></a>  <span class="co">#   freq &lt;- nobs</span></span>
<span id="cb17-47"><a href="#cb17-47" aria-hidden="true" tabindex="-1"></a>  <span class="co"># }</span></span>
<span id="cb17-48"><a href="#cb17-48" aria-hidden="true" tabindex="-1"></a>  freq <span class="ot">&lt;-</span> <span class="fu">calc.freq</span>(datetime)</span>
<span id="cb17-49"><a href="#cb17-49" aria-hidden="true" tabindex="-1"></a>  do.diff <span class="ot">&lt;-</span> <span class="fu">diff</span>(do.obs)</span>
<span id="cb17-50"><a href="#cb17-50" aria-hidden="true" tabindex="-1"></a>  inst_flux <span class="ot">&lt;-</span> (k.gas<span class="sc">/</span>freq) <span class="sc">*</span> (do.sat <span class="sc">-</span> do.obs)</span>
<span id="cb17-51"><a href="#cb17-51" aria-hidden="true" tabindex="-1"></a>  flux <span class="ot">&lt;-</span> inst_flux[<span class="sc">-</span>nobs]</span>
<span id="cb17-52"><a href="#cb17-52" aria-hidden="true" tabindex="-1"></a>  noflux.do.diff <span class="ot">&lt;-</span> do.diff <span class="sc">-</span> flux<span class="sc">/</span>z.mix[<span class="sc">-</span>nobs]</span>
<span id="cb17-53"><a href="#cb17-53" aria-hidden="true" tabindex="-1"></a>  lntemp <span class="ot">&lt;-</span> <span class="fu">log</span>(wtr)</span>
<span id="cb17-54"><a href="#cb17-54" aria-hidden="true" tabindex="-1"></a>  mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(noflux.do.diff <span class="sc">~</span> irr[<span class="sc">-</span>nobs] <span class="sc">+</span> lntemp[<span class="sc">-</span>nobs] <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb17-55"><a href="#cb17-55" aria-hidden="true" tabindex="-1"></a>  rho <span class="ot">&lt;-</span> mod[[<span class="dv">1</span>]][<span class="dv">2</span>]</span>
<span id="cb17-56"><a href="#cb17-56" aria-hidden="true" tabindex="-1"></a>  iota <span class="ot">&lt;-</span> mod[[<span class="dv">1</span>]][<span class="dv">1</span>]</span>
<span id="cb17-57"><a href="#cb17-57" aria-hidden="true" tabindex="-1"></a>  mod.matrix <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(mod)</span>
<span id="cb17-58"><a href="#cb17-58" aria-hidden="true" tabindex="-1"></a>  gpp <span class="ot">&lt;-</span> iota <span class="sc">*</span> mod.matrix[, <span class="dv">1</span>]<span class="sc">*</span>freq</span>
<span id="cb17-59"><a href="#cb17-59" aria-hidden="true" tabindex="-1"></a>  resp <span class="ot">&lt;-</span> rho <span class="sc">*</span> mod.matrix[, <span class="dv">2</span>]<span class="sc">*</span>freq</span>
<span id="cb17-60"><a href="#cb17-60" aria-hidden="true" tabindex="-1"></a>  nep <span class="ot">&lt;-</span> gpp <span class="sc">+</span> resp</span>
<span id="cb17-61"><a href="#cb17-61" aria-hidden="true" tabindex="-1"></a>  datetime <span class="ot">&lt;-</span> datetime[<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb17-62"><a href="#cb17-62" aria-hidden="true" tabindex="-1"></a>  inst.results <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">mod =</span> mod, <span class="at">metab =</span> <span class="fu">data.frame</span>(<span class="at">datetime =</span> datetime, <span class="at">GPP =</span> gpp, </span>
<span id="cb17-63"><a href="#cb17-63" aria-hidden="true" tabindex="-1"></a>                                                <span class="at">R =</span> resp, <span class="at">NEP =</span> nep, <span class="at">KO2 =</span> k.gas[<span class="sc">-</span>nobs]))</span>
<span id="cb17-64"><a href="#cb17-64" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(inst.results)</span>
<span id="cb17-65"><a href="#cb17-65" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="hypothesis-tests" class="level3">
<h3 class="anchored" data-anchor-id="hypothesis-tests">Hypothesis Tests</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter daytime data where PAR &gt; 0 (indicative of sunlight hours)</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>daytime_data <span class="ot">&lt;-</span> ts.data[ts.data<span class="sc">$</span>par <span class="sc">&gt;</span> <span class="dv">0</span>, ]</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate correlation between PAR and GPP</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(daytime_data<span class="sc">$</span>par, ols.inst.res.df<span class="sc">$</span>GPP[ts.data<span class="sc">$</span>par <span class="sc">&gt;</span> <span class="dv">0</span>], <span class="at">method =</span> <span class="st">"pearson"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  daytime_data$par and ols.inst.res.df$GPP[ts.data$par &gt; 0]
t = 222574922, df = 22, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 1 1
sample estimates:
cor 
  1 </code></pre>
</div>
</div>
<p>To examine the relationship between light availability and ecosystem productivity, a Pearson correlation test was conducted between PAR (photosynthetically active radiation) and GPP (gross primary production) during the daytime period (when PAR &gt; 0). The results showed an <strong>extremely strong positive correlation</strong> between PAR and GPP, with a correlation coefficient of <strong>r = 1</strong> and a <strong>p-value &lt; 2.2e-16</strong>, indicating that the relationship is statistically significant. This confirms that GPP increases with light intensity and is tightly coupled with solar radiation availability, as expected in photosynthetically driven aquatic systems. The strength of this correlation validates the role of PAR as a key environmental driver of primary productivity in Stephens Lake during the fall sampling period.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define day and night based on PAR threshold</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>ols.inst.res.df<span class="sc">$</span>light_period <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(ts.data<span class="sc">$</span>par[<span class="sc">-</span><span class="dv">1</span>] <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="st">"Day"</span>, <span class="st">"Night"</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform t-test comparing NEP between day and night</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(NEP <span class="sc">~</span> light_period, <span class="at">data =</span> ols.inst.res.df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  NEP by light_period
t = 9.3664, df = 24.276, p-value = 1.56e-09
alternative hypothesis: true difference in means between group Day and group Night is not equal to 0
95 percent confidence interval:
 4.196126 6.566203
sample estimates:
  mean in group Day mean in group Night 
          0.1347573          -5.2464069 </code></pre>
</div>
</div>
<p>To evaluate differences in Net Ecosystem Productivity (NEP) between day and night, a Welch Two Sample t-test was conducted. The results show a <strong>statistically significant difference</strong> in NEP between these two light periods (<strong>t = 9.37</strong>, <strong>df = 24.28</strong>, <strong>p &lt; 0.000000002</strong>). The 95% confidence interval for the difference in means ranges from <strong>4.20 to 6.57</strong>, suggesting that this difference is not due to random variation.</p>
<p>Specifically, the mean NEP during the <strong>day</strong> was <strong>+0.13 mg O₂/L/hr</strong>, indicating slight net oxygen production, while the mean NEP at <strong>night</strong> was <strong>−5.25 mg O₂/L/hr</strong>, signifying dominant ecosystem respiration. These results provide strong support for <strong>Hypothesis 3 (H3)</strong> — that NEP is positive during sunlight hours and negative during the night, reflecting typical diel metabolic behavior in oligotrophic lakes.</p>
</section>
<section id="results-and-discussion" class="level3">
<h3 class="anchored" data-anchor-id="results-and-discussion">Results and Discussion</h3>
<p>Before modeling lake metabolism, I conducted basic exploratory data analysis on the key variables: dissolved oxygen (DO), water temperature, wind speed, and photosynthetically active radiation (PAR). The dataset consists of 48 hourly observations over two full days (October 18–20, 2024), capturing the diel variability in environmental conditions.</p>
<p>DO concentrations at 0.5 meters depth ranged from approximately <strong>8.2 to 10.5 mg/L</strong>, with higher values observed during midday hours, consistent with photosynthetic oxygen production. Water temperature varied modestly across the diel cycle, ranging between <strong>17.8°C and 19.2°C</strong>, reflecting the thermal inertia typical of shallow lakes in fall. Wind speed, extracted from the ERA5-Land dataset and converted to standard 10-meter height (U10), ranged from <strong>0.1 to 3.8 m/s</strong>, influencing surface gas exchange. PAR values modeled using the <code>suncalc</code> package ranged from <strong>0 to ~1700 μmol/m²/s</strong>, with clear peaks during mid-day and zero values at night, validating expected sunlight-driven patterns.</p>
<p>The dataset captures sufficient diel variation to support metabolism modeling, especially the contrasting light and dark conditions necessary to distinguish GPP, ER, and NEP dynamics. Below is the final GPP-ER-NEP plot with nighttime shaded and custom x-axis labeling.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>ols.inst.res <span class="ot">=</span> <span class="fu">OLS_inst</span>(<span class="at">datetime =</span> ts.data<span class="sc">$</span>datetime, </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">do.obs =</span> ts.data<span class="sc">$</span>doobs_0<span class="fl">.5</span>, <span class="at">do.sat =</span> ts.data<span class="sc">$</span>do.sat,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">k.gas =</span> ts.data<span class="sc">$</span>k.gas, <span class="at">z.mix =</span> ts.data<span class="sc">$</span>z.mix,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">irr =</span> ts.data<span class="sc">$</span>par, <span class="at">wtr =</span> ts.data<span class="sc">$</span>wtr_0<span class="fl">.5</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Get error message when I run the following line</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co">#write.csv(ols.inst.res$metab, 'LakeAnalyzer/metab.ols.inst.csv', row.names=FALSE)</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>ols.inst.res.df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(ols.inst.res<span class="sc">$</span>metab)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ols.inst.res.df<span class="sc">$</span>datetime, ols.inst.res.df<span class="sc">$</span>GPP, <span class="at">type=</span><span class="st">"l"</span>, <span class="at">col=</span><span class="st">"blue"</span>, <span class="at">ylim=</span><span class="fu">range</span>(ols.inst.res.df[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>]), <span class="at">ylab=</span><span class="st">"Metabolism (mg O2/L/hr)"</span>, <span class="at">xlab=</span><span class="st">"Datetime"</span>)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="fu">axis.POSIXct</span>(<span class="dv">1</span>,</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">at =</span> <span class="fu">as.POSIXct</span>(<span class="fu">c</span>(<span class="st">"2024-10-18 18:15"</span>, <span class="st">"2024-10-19 07:00"</span>,</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"2024-10-19 18:15"</span>, <span class="st">"2024-10-20 07:00"</span>), <span class="at">tz =</span> <span class="st">"UTC"</span>),</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"18:15"</span>, <span class="st">"07:00"</span>, <span class="st">"18:15"</span>, <span class="st">"07:00"</span>),</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">cex.axis =</span> <span class="fl">0.8</span>,</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>             <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>             <span class="at">tick =</span> <span class="cn">TRUE</span>)</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Add nighttime shading (two periods)</span></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a><span class="fu">rect</span>(<span class="fu">as.POSIXct</span>(<span class="st">"2024-10-18 18:15"</span>, <span class="at">tz =</span> <span class="st">"UTC"</span>), <span class="sc">-</span><span class="dv">100</span>,</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>     <span class="fu">as.POSIXct</span>(<span class="st">"2024-10-19 07:00"</span>, <span class="at">tz =</span> <span class="st">"UTC"</span>), <span class="dv">100</span>,</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="fu">rgb</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="fl">0.1</span>), <span class="at">border =</span> <span class="cn">NA</span>)</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a><span class="fu">rect</span>(<span class="fu">as.POSIXct</span>(<span class="st">"2024-10-19 18:15"</span>, <span class="at">tz =</span> <span class="st">"UTC"</span>), <span class="sc">-</span><span class="dv">100</span>,</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>     <span class="fu">as.POSIXct</span>(<span class="st">"2024-10-20 07:00"</span>, <span class="at">tz =</span> <span class="st">"UTC"</span>), <span class="dv">100</span>,</span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="fu">rgb</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="fl">0.1</span>), <span class="at">border =</span> <span class="cn">NA</span>)</span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(ols.inst.res.df<span class="sc">$</span>datetime, ols.inst.res.df<span class="sc">$</span>R, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(ols.inst.res.df<span class="sc">$</span>datetime, ols.inst.res.df<span class="sc">$</span>NEP, <span class="at">col=</span><span class="st">"green"</span>)</span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>,</span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"GPP"</span>, <span class="st">"ER"</span>, <span class="st">"NEP"</span>),</span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"red"</span>, <span class="st">"green"</span>),</span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="dv">1</span>,</span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a>       <span class="at">bty =</span> <span class="st">"n"</span>)  <span class="co"># This removes the legend background and border</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="semester-project_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="key-observations" class="level3">
<h3 class="anchored" data-anchor-id="key-observations">Key observations:</h3>
<p>The ecosystem metabolism results revealed strong diel trends consistent with theoretical expectations for oligotrophic headwater lakes. <strong>Gross Primary Production (GPP)</strong> exhibited a pronounced mid-day peak between <strong>11:00 and 15:00</strong> on both sampling days, reaching values of approximately <strong>9.5–10.0 mg O₂/L/hr</strong>. This timing aligned closely with the daily maxima in modeled <strong>Photosynthetically Active Radiation (PAR)</strong>, confirming the dependency of GPP on light availability. The GPP curve showed a steep rise shortly after sunrise and a rapid decline toward evening, with near-zero values during the nighttime hours.</p>
<p><strong>Ecosystem Respiration (ER)</strong> remained relatively stable throughout the diel cycle, ranging between <strong>-4.5 and -5.0 mg O₂/L/hr</strong>. While slight increases were observed during nighttime hours—likely reflecting microbial and planktonic respiration—the variation in ER was modest compared to the dynamic behavior of GPP.</p>
<p><strong>Net Ecosystem Production (NEP)</strong> clearly captured the transition between photosynthetic and respiratory dominance. NEP was consistently <strong>positive during daylight hours</strong>, indicating a net autotrophic state (GPP &gt; ER), and <strong>negative at night</strong>, reflecting a shift to net heterotrophy as GPP dropped to zero and ER continued. The sharp inflection points around dawn and dusk highlight the effectiveness of high-frequency sampling in resolving transient metabolic processes.</p>
<p>These trends affirm that the system is primarily light-driven, and that diel patterns of metabolism in Stephens Lake are strongly regulated by solar radiation and its effect on photosynthesis.</p>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>This study successfully applied the LakeMetabolizer package in R to model diel changes in aquatic metabolism over a 48-hour fall period in Stephens Lake, Franklin, Tennessee. The combination of in situ dissolved oxygen and temperature measurements, modeled wind speed from ERA5-Land, and solar irradiance from the <code>suncalc</code> package enabled robust estimation of GPP, ER, and NEP. GPP showed strong diel peaks aligned with sunlight availability. ER remained relatively constant, indicating stable respiratory processes. NEP shifted between positive and negative values, clearly tracking daily light cycles. These results reinforce the central role of light in controlling primary production and carbon cycling in small headwater lakes. The use of open-access data (ERA5 for wind and modeled PAR) and open-source tools makes this workflow replicable and scalable for other aquatic ecosystems.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>